FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip git

RUN pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu126


RUN git clone https://github.com/sugoma11/InconvenientWeightsUpdate
# WORKDIR InconvenientWeightsUpdate

CMD ["python3", "main_triu.py"]